In [6]:
import numpy as np
import pandas as pd

In [7]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data) #multiple data series creates data frame  (key are the header/column)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
data_list = [
['John', 28, 'New York', 65000],
['Anna', 34, 'Paris', 70000],
['Peter', 29, 'Berlin', 62000],
['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)

In [9]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [19]:
data_list = [
['John', 28, 'New York', 65000],
['Anna', 34, 'Paris', 70000],
['Peter', 29, 'Berlin', 62000],
['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
columns=['name','age','city','salary']
label=['a','b','c','d']
df2=pd.DataFrame(data_list,columns=columns,index=label)

In [20]:
df2

    name  age      city  salary
a   John   28  New York   65000
b   Anna   34     Paris   70000
c  Peter   29    Berlin   62000
d  Linda   42    London   85000

In [9]:
#Selection and Indexing of columns

In [10]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
df2['name']

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: str

In [12]:
df2['city']

0    New York
1       Paris
2      Berlin
3      London
Name: city, dtype: str

In [13]:
df2[['name','city','age']]

    name      city  age
0   John  New York   28
1   Anna     Paris   34
2  Peter    Berlin   29
3  Linda    London   42

In [14]:
df2['designation']=['engineer','doc','mc','ca']

In [15]:
df2

    name  age      city  salary designation
0   John   28  New York   65000    engineer
1   Anna   34     Paris   70000         doc
2  Peter   29    Berlin   62000          mc
3  Linda   42    London   85000          ca

In [16]:
df2.drop('designation',axis=1) # axis -> 1 = column axis -> 0 = row

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [17]:
df2.drop(0,axis=0)

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [18]:
df2 #however orignally nothing happend drop only shoes copy

    name  age      city  salary designation
0   John   28  New York   65000    engineer
1   Anna   34     Paris   70000         doc
2  Peter   29    Berlin   62000          mc
3  Linda   42    London   85000          ca

In [19]:
df2.drop('designation',axis=1,inplace=True);
df2 #inplace removes permamnently

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
df3=df2.drop(["city","salary"],axis=1,inplace=False);
df3

    name  age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [21]:
df4=df2.loc[0]
df4

name          John
age             28
city      New York
salary       65000
Name: 0, dtype: object

In [22]:
df5=df2.loc[[0,1]]
df5

   name  age      city  salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [23]:
#selecting subset of rows and column

In [25]:
df2.loc[[0,1]][['city','salary']]

       city  salary
0  New York   65000
1     Paris   70000

In [26]:
df2.loc[[2,3]][['name','age']]

    name  age
2  Peter   29
3  Linda   42

In [ ]:
# Conditional Selection

In [34]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [35]:
# I only want to see people of age more than 30
df2[df2['age'] > 30]

    name  age    city  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [37]:
# i only want people whose age is above 30 and their city must be paris
df2[(df2["age"] > 30) & (df2["city"] == 'Paris')]

   name  age   city  salary
1  Anna   34  Paris   70000