In [1]:
import numpy as np
import pandas as pd

In [ ]:
#Finding Missing Value

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [3]:
df.isna() #False-> not a null

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [4]:
df.isna().sum() #total null value in each row

A    1
B    1
C    2
D    3
dtype: int64

In [5]:
df.isna().any() # any row contain null value

A    True
B    True
C    True
D    True
dtype: bool

In [ ]:
#Removing Missing data

In [6]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df2 = pd.DataFrame(data)
df2

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [7]:
df2.dropna() #drop all rows with null value

     A  B    C    D
0  1.0  1  1.0  1.0

In [8]:
df2.dropna(thresh=3) #remove row that has not minimum no of not null value

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [ ]:
#Filling Missing data

In [9]:
df2

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [13]:
df2.fillna(value=0) # NaN <-> 0

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [20]:
replace={"A":1000,"B":2000,"C":3000,"D":4000}
df2.fillna(value=replace)

        A  B       C       D
0     1.0  1     1.0     1.0
1     2.0  2     2.0  4000.0
2  1000.0  3     3.0  4000.0
3     4.0  4  3000.0  4000.0
4     5.0  5  3000.0     5.0