In [1]:
import numpy as np
import pandas as pd

Basic Operations

In [2]:
df1 = pd.DataFrame({
'A': [1, 2, 3, 4, 5],
'B': [10, 20, 30, 40, 50],
'C': [100, 200, 300, 400, 500]
})

In [3]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [6]:
df1.shape

(5, 3)

In [7]:
df1.info

<bound method DataFrame.info of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [8]:
df1.describe

<bound method NDFrame.describe of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [9]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [10]:
df1.index

RangeIndex(start=0, stop=5, step=1)

In [24]:
df1['A']=df1['A']+10
df1

    A   B    C
0  31  10  100
1  32  20  200
2  33  30  300
3  34  40  400
4  35  50  500

Applying functions

In [19]:
def square(x):
    return x**2

In [20]:
df1.apply(square)

    A     B       C
0   1   100   10000
1   4   400   40000
2   9   900   90000
3  16  1600  160000
4  25  2500  250000

In [21]:
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64